### ISSUE TITLE
Folllowing the README.md file the application not working

### ISSUE THREAD

**Issue by SudalaiVJ** [INRIM/service-app#2]
Facing ImportError: cannot import name 'lru_cache' from 'pydantic.tools' (/usr/local/lib/python3.11/site-packages/pydantic/tools.py) in backend and webclient. and automation container also existed.

**Comment by archetipo** [comment]
Hi @SudalaiVJ 

 thanks .
 Can you please  pull code and  try to follow the README again?

**Comment by SudalaiVJ** [comment]
Thanks, @archetipo 
Now It's Working.
